### PR TITLE
Wrapper scripts

### PR DESCRIPTION
**Pull request by UnixJunkie**
Hello,

Here are two handy scripts:
bin/rxnmap.py: atom-atom map a .rsmi file (reaction SMILES)
bin/rsmi_center.py: compute chemical distance and extract reaction centers from a mapped .rsmi file

Regards,
F.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
@pschwllr Not interested?

**Comment by UnixJunkie** [comment]
Why was this PR closed?

**Comment by avaucher** [comment]
Sorry for that. I think that GitHub closed it automatically when I deleted the `master` branch - and now I can't reopen it.

**Comment by UnixJunkie** [comment]
Do you want me to submit it again?
It has waited quite some time without any feedback, so I don't think you are interested though.

**Comment by avaucher** [comment]
To be honest, I haven't looked at the PR yet. But independently of that, I am in the process of checking the legal aspects of external contributions to our repos. Let me get back to you within the coming weeks :)

**Pull request closed without merging**
