### PR TITLE
Freeze to Transformers 4.0

### PR DESCRIPTION
**Pull request by bhoov**
Remove warnings + errors caused by deprecations. 

Do you agree with the frozen versions?

### CODE REVIEW

**Comment by pschwllr** [comment]
The requirements in the `setup.py` file are not the same as in requirements.txt.

**Comment by pschwllr** [comment]
Otherwise it is looking good, the example works. The tests are passing.

**Comment by bhoov** [comment]
Good catch. Better?

**Review by pschwllr — APPROVED** [review]
Approved.

**Pull request merged**
